// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529093514_AddProfileFields")]
    partial class AddProfileFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Doctors.DoctorAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("integer")
                        .HasColumnName("auth_provider");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleSubId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_sub_id");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_doctor_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_doctor_accounts_email");

                    b.HasIndex("GoogleSubId")
                        .IsUnique()
                        .HasDatabaseName("ix_doctor_accounts_google_sub_id")
                        .HasFilter("google_sub_id IS NOT NULL");

                    b.ToTable("doctor_accounts", "public");
                });

            modelBuilder.Entity("Domain.Doctors.DoctorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<int>("CompletionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("completion_status");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("NicNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nic_number");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("profile_picture_url");

                    b.PrimitiveCollection<string[]>("Qualifications")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("qualifications");

                    b.Property<string>("SlmcRegNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slmc_reg_number");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialty");

                    b.HasKey("Id")
                        .HasName("pk_doctor_profiles");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_doctor_profiles_account_id");

                    b.HasIndex("NicNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_doctor_profiles_nic_number")
                        .HasFilter("nic_number IS NOT NULL");

                    b.HasIndex("SlmcRegNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_doctor_profiles_slmc_reg_number")
                        .HasFilter("slmc_reg_number IS NOT NULL");

                    b.ToTable("doctor_profiles", "public");
                });

            modelBuilder.Entity("Domain.Doctors.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_url");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_documents_profile_id");

                    b.ToTable("documents", "public");
                });

            modelBuilder.Entity("Domain.Doctors.ESignature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("SignatureDataUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signature_data_url");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_at");

                    b.HasKey("Id")
                        .HasName("pk_e_signatures");

                    b.HasIndex("ProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_e_signatures_profile_id");

                    b.ToTable("e_signatures", "public");
                });

            modelBuilder.Entity("Domain.Doctors.OtpSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("otp_hash");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id")
                        .HasName("pk_otp_sessions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_otp_sessions_account_id");

                    b.ToTable("otp_sessions", "public");
                });

            modelBuilder.Entity("Domain.Doctors.PracticeIdentity", b =>
                {
                    b.Property<string>("PracticeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("practice_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("BarcodeData")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("barcode_data");

                    b.HasKey("PracticeId")
                        .HasName("pk_practice_identities");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_practice_identities_account_id");

                    b.ToTable("practice_identities", "public");
                });

            modelBuilder.Entity("Domain.Doctors.VerificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuditedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audited_by");

                    b.Property<bool>("BadgeAwarded")
                        .HasColumnType("boolean")
                        .HasColumnName("badge_awarded");

                    b.Property<bool>("DocumentsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("documents_verified");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<bool>("QualificationsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("qualifications_verified");

                    b.Property<bool>("SlmcVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("slmc_verified");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_verification_records");

                    b.HasIndex("ProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_verification_records_profile_id");

                    b.ToTable("verification_records", "public");
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.PrimitiveCollection<List<string>>("Labels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("labels");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_todo_items");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_todo_items_user_id");

                    b.ToTable("todo_items", "public");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Domain.Doctors.DoctorProfile", b =>
                {
                    b.HasOne("Domain.Doctors.DoctorAccount", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("Domain.Doctors.DoctorProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doctor_profiles_doctor_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Domain.Doctors.Document", b =>
                {
                    b.HasOne("Domain.Doctors.DoctorProfile", "Profile")
                        .WithMany("Documents")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_doctor_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Doctors.ESignature", b =>
                {
                    b.HasOne("Domain.Doctors.DoctorProfile", "Profile")
                        .WithOne("ESignature")
                        .HasForeignKey("Domain.Doctors.ESignature", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_e_signatures_doctor_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Doctors.OtpSession", b =>
                {
                    b.HasOne("Domain.Doctors.DoctorAccount", "Account")
                        .WithMany("OtpSessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otp_sessions_doctor_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Domain.Doctors.PracticeIdentity", b =>
                {
                    b.HasOne("Domain.Doctors.DoctorAccount", "Account")
                        .WithOne("PracticeIdentity")
                        .HasForeignKey("Domain.Doctors.PracticeIdentity", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_practice_identities_doctor_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Domain.Doctors.VerificationRecord", b =>
                {
                    b.HasOne("Domain.Doctors.DoctorProfile", "Profile")
                        .WithOne("VerificationRecord")
                        .HasForeignKey("Domain.Doctors.VerificationRecord", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verification_records_doctor_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_items_users_user_id");
                });

            modelBuilder.Entity("Domain.Doctors.DoctorAccount", b =>
                {
                    b.Navigation("OtpSessions");

                    b.Navigation("PracticeIdentity");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Doctors.DoctorProfile", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("ESignature");

                    b.Navigation("VerificationRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
