// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260720153354_AddPatientQueueTickets")]
    partial class AddPatientQueueTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Doctors.DoctorAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("integer")
                        .HasColumnName("auth_provider");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleSubId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_sub_id");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_doctor_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_doctor_accounts_email");

                    b.HasIndex("GoogleSubId")
                        .IsUnique()
                        .HasDatabaseName("ix_doctor_accounts_google_sub_id")
                        .HasFilter("google_sub_id IS NOT NULL");

                    b.ToTable("doctor_accounts", "public");
                });

            modelBuilder.Entity("Domain.Doctors.DoctorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Bio")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("bio");

                    b.Property<int>("CompletionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("completion_status");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("NicNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nic_number");

                    b.Property<string>("ProfilePictureContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("profile_picture_content_type");

                    b.Property<byte[]>("ProfilePictureData")
                        .HasColumnType("bytea")
                        .HasColumnName("profile_picture_data");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("profile_picture_url");

                    b.PrimitiveCollection<string[]>("Qualifications")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("qualifications");

                    b.Property<string>("SlmcRegNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slmc_reg_number");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialty");

                    b.Property<string>("SubSpecialty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sub_specialty");

                    b.HasKey("Id")
                        .HasName("pk_doctor_profiles");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_doctor_profiles_account_id");

                    b.HasIndex("NicNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_doctor_profiles_nic_number")
                        .HasFilter("nic_number IS NOT NULL");

                    b.HasIndex("SlmcRegNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_doctor_profiles_slmc_reg_number")
                        .HasFilter("slmc_reg_number IS NOT NULL");

                    b.ToTable("doctor_profiles", "public");
                });

            modelBuilder.Entity("Domain.Doctors.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("bytea")
                        .HasColumnName("file_data");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_documents_profile_id");

                    b.ToTable("documents", "public");
                });

            modelBuilder.Entity("Domain.Doctors.ESignature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("SignatureContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("signature_content_type");

                    b.Property<byte[]>("SignatureData")
                        .HasColumnType("bytea")
                        .HasColumnName("signature_data");

                    b.Property<string>("SignatureDataUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signature_data_url");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_at");

                    b.HasKey("Id")
                        .HasName("pk_e_signatures");

                    b.HasIndex("ProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_e_signatures_profile_id");

                    b.ToTable("e_signatures", "public");
                });

            modelBuilder.Entity("Domain.Doctors.OtpSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("otp_hash");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id")
                        .HasName("pk_otp_sessions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_otp_sessions_account_id");

                    b.ToTable("otp_sessions", "public");
                });

            modelBuilder.Entity("Domain.Doctors.PracticeIdentity", b =>
                {
                    b.Property<string>("PracticeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("practice_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("BarcodeData")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("barcode_data");

                    b.HasKey("PracticeId")
                        .HasName("pk_practice_identities");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_practice_identities_account_id");

                    b.ToTable("practice_identities", "public");
                });

            modelBuilder.Entity("Domain.Doctors.Qualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("CertificateContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("certificate_content_type");

                    b.Property<byte[]>("CertificateData")
                        .HasColumnType("bytea")
                        .HasColumnName("certificate_data");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("Id")
                        .HasName("pk_qualifications");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_qualifications_profile_id");

                    b.ToTable("qualifications", "public");
                });

            modelBuilder.Entity("Domain.Doctors.VerificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuditedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("audited_by");

                    b.Property<bool>("BadgeAwarded")
                        .HasColumnType("boolean")
                        .HasColumnName("badge_awarded");

                    b.Property<bool>("DocumentsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("documents_verified");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<bool>("QualificationsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("qualifications_verified");

                    b.Property<bool>("SlmcVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("slmc_verified");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_verification_records");

                    b.HasIndex("ProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_verification_records_profile_id");

                    b.ToTable("verification_records", "public");
                });

            modelBuilder.Entity("Domain.Favorites.FavoriteMedicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerifiedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("verified_name");

                    b.HasKey("Id")
                        .HasName("pk_favorite_medicines");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("ix_favorite_medicines_doctor_id");

                    b.ToTable("favorite_medicines", "public");
                });

            modelBuilder.Entity("Domain.Locations.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_districts");

                    b.ToTable("districts", "public");
                });

            modelBuilder.Entity("Domain.Locations.MohArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("district_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_moh_areas");

                    b.HasIndex("DistrictId")
                        .HasDatabaseName("ix_moh_areas_district_id");

                    b.ToTable("moh_areas", "public");
                });

            modelBuilder.Entity("Domain.Locations.Place", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<Guid>("MohAreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("moh_area_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_places");

                    b.HasIndex("MohAreaId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_places_moh_area_id_name");

                    b.ToTable("places", "public");
                });

            modelBuilder.Entity("Domain.PatientQueue.PatientQueueTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("called_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<string>("PatientMobile")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_mobile");

                    b.Property<Guid>("PracticeCentreId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_centre_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("integer")
                        .HasColumnName("queue_number");

                    b.Property<int>("QueueOrder")
                        .HasColumnType("integer")
                        .HasColumnName("queue_order");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("date")
                        .HasColumnName("visit_date");

                    b.HasKey("Id")
                        .HasName("pk_patient_queue_ticket");

                    b.HasIndex("PracticeCentreId", "DoctorId", "VisitDate", "Status")
                        .HasDatabaseName("ix_patient_queue_ticket_practice_centre_id_doctor_id_visit_date_");

                    b.ToTable("PatientQueueTicket", "public");
                });

            modelBuilder.Entity("Domain.Patients.PatientAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CompletionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("completion_status");

                    b.Property<Guid?>("CreatedByDoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_doctor_id");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("NicNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nic_number");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id")
                        .HasName("pk_patient_accounts");

                    b.HasIndex("CreatedByDoctorId")
                        .HasDatabaseName("ix_patient_accounts_created_by_doctor_id");

                    b.HasIndex("NicNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_patient_accounts_nic_number");

                    b.ToTable("patient_accounts", "public");
                });

            modelBuilder.Entity("Domain.Patients.PatientDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("bytea")
                        .HasColumnName("file_data");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("PatientAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_account_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_patient_documents");

                    b.HasIndex("PatientAccountId")
                        .HasDatabaseName("ix_patient_documents_patient_account_id");

                    b.ToTable("patient_documents", "public");
                });

            modelBuilder.Entity("Domain.PracticeCentres.Nurse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("PracticeCentreId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_centre_id");

                    b.HasKey("Id")
                        .HasName("pk_nurses");

                    b.HasIndex("PracticeCentreId")
                        .HasDatabaseName("ix_nurses_practice_centre_id");

                    b.ToTable("nurses", "public");
                });

            modelBuilder.Entity("Domain.PracticeCentres.PracticeCentre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("clinic_name");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<int?>("MaxPatients")
                        .HasColumnType("integer")
                        .HasColumnName("max_patients");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.HasKey("Id")
                        .HasName("pk_practice_centres");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("ix_practice_centres_doctor_id");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_practice_centres_place_id");

                    b.ToTable("practice_centres", "public");
                });

            modelBuilder.Entity("Domain.PracticeCentres.SessionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DaysOfWeekRaw")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("days_of_week_raw");

                    b.Property<Guid>("PracticeCentreId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_centre_id");

                    b.HasKey("Id")
                        .HasName("pk_session_groups");

                    b.HasIndex("PracticeCentreId")
                        .HasDatabaseName("ix_session_groups_practice_centre_id");

                    b.ToTable("session_groups", "public");
                });

            modelBuilder.Entity("Domain.PracticeCentres.TimeBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<Guid>("SessionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_group_id");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_time_blocks");

                    b.HasIndex("SessionGroupId")
                        .HasDatabaseName("ix_time_blocks_session_group_id");

                    b.ToTable("time_blocks", "public");
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.PrimitiveCollection<List<string>>("Labels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("labels");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_todo_items");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_todo_items_user_id");

                    b.ToTable("todo_items", "public");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Domain.Doctors.DoctorProfile", b =>
                {
                    b.HasOne("Domain.Doctors.DoctorAccount", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("Domain.Doctors.DoctorProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doctor_profiles_doctor_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Domain.Doctors.Document", b =>
                {
                    b.HasOne("Domain.Doctors.DoctorProfile", "Profile")
                        .WithMany("Documents")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_doctor_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Doctors.ESignature", b =>
                {
                    b.HasOne("Domain.Doctors.DoctorProfile", "Profile")
                        .WithOne("ESignature")
                        .HasForeignKey("Domain.Doctors.ESignature", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_e_signatures_doctor_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Doctors.OtpSession", b =>
                {
                    b.HasOne("Domain.Doctors.DoctorAccount", "Account")
                        .WithMany("OtpSessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otp_sessions_doctor_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Domain.Doctors.PracticeIdentity", b =>
                {
                    b.HasOne("Domain.Doctors.DoctorAccount", "Account")
                        .WithOne("PracticeIdentity")
                        .HasForeignKey("Domain.Doctors.PracticeIdentity", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_practice_identities_doctor_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Domain.Doctors.Qualification", b =>
                {
                    b.HasOne("Domain.Doctors.DoctorProfile", "Profile")
                        .WithMany("QualificationsList")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_qualifications_doctor_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Doctors.VerificationRecord", b =>
                {
                    b.HasOne("Domain.Doctors.DoctorProfile", "Profile")
                        .WithOne("VerificationRecord")
                        .HasForeignKey("Domain.Doctors.VerificationRecord", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verification_records_doctor_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Favorites.FavoriteMedicine", b =>
                {
                    b.HasOne("Domain.Doctors.DoctorAccount", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorite_medicines_doctor_accounts_doctor_id");
                });

            modelBuilder.Entity("Domain.Locations.MohArea", b =>
                {
                    b.HasOne("Domain.Locations.District", "District")
                        .WithMany("MohAreas")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_moh_areas_districts_district_id");

                    b.Navigation("District");
                });

            modelBuilder.Entity("Domain.Locations.Place", b =>
                {
                    b.HasOne("Domain.Locations.MohArea", "MohArea")
                        .WithMany("Places")
                        .HasForeignKey("MohAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_places_moh_areas_moh_area_id");

                    b.Navigation("MohArea");
                });

            modelBuilder.Entity("Domain.Patients.PatientAccount", b =>
                {
                    b.HasOne("Domain.Doctors.DoctorAccount", "CreatedByDoctor")
                        .WithMany()
                        .HasForeignKey("CreatedByDoctorId")
                        .HasConstraintName("fk_patient_accounts_doctor_accounts_created_by_doctor_id");

                    b.Navigation("CreatedByDoctor");
                });

            modelBuilder.Entity("Domain.Patients.PatientDocument", b =>
                {
                    b.HasOne("Domain.Patients.PatientAccount", "PatientAccount")
                        .WithMany("Documents")
                        .HasForeignKey("PatientAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_documents_patient_accounts_patient_account_id");

                    b.Navigation("PatientAccount");
                });

            modelBuilder.Entity("Domain.PracticeCentres.Nurse", b =>
                {
                    b.HasOne("Domain.PracticeCentres.PracticeCentre", "PracticeCentre")
                        .WithMany("Nurses")
                        .HasForeignKey("PracticeCentreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nurses_practice_centres_practice_centre_id");

                    b.Navigation("PracticeCentre");
                });

            modelBuilder.Entity("Domain.PracticeCentres.PracticeCentre", b =>
                {
                    b.HasOne("Domain.Doctors.DoctorAccount", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_practice_centres_doctor_accounts_doctor_id");

                    b.HasOne("Domain.Locations.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_practice_centres_places_place_id");

                    b.Navigation("Doctor");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Domain.PracticeCentres.SessionGroup", b =>
                {
                    b.HasOne("Domain.PracticeCentres.PracticeCentre", "PracticeCentre")
                        .WithMany("SessionGroups")
                        .HasForeignKey("PracticeCentreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_groups_practice_centres_practice_centre_id");

                    b.Navigation("PracticeCentre");
                });

            modelBuilder.Entity("Domain.PracticeCentres.TimeBlock", b =>
                {
                    b.HasOne("Domain.PracticeCentres.SessionGroup", "SessionGroup")
                        .WithMany("TimeBlocks")
                        .HasForeignKey("SessionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_time_blocks_session_groups_session_group_id");

                    b.Navigation("SessionGroup");
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_items_users_user_id");
                });

            modelBuilder.Entity("Domain.Doctors.DoctorAccount", b =>
                {
                    b.Navigation("OtpSessions");

                    b.Navigation("PracticeIdentity");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Doctors.DoctorProfile", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("ESignature");

                    b.Navigation("QualificationsList");

                    b.Navigation("VerificationRecord");
                });

            modelBuilder.Entity("Domain.Locations.District", b =>
                {
                    b.Navigation("MohAreas");
                });

            modelBuilder.Entity("Domain.Locations.MohArea", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("Domain.Patients.PatientAccount", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Domain.PracticeCentres.PracticeCentre", b =>
                {
                    b.Navigation("Nurses");

                    b.Navigation("SessionGroups");
                });

            modelBuilder.Entity("Domain.PracticeCentres.SessionGroup", b =>
                {
                    b.Navigation("TimeBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
